
// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.IO;

namespace RickAndMortyTrain.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            var imageBytes = File.ReadAllBytes(@"C:\Repository\Learning\MlWorkshop\Train\morty\m (1).jpg");
            RickAndMortyTrain.ModelInput sampleData = new RickAndMortyTrain.ModelInput()
            {
                ImageSource = imageBytes,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = RickAndMortyTrain.Predict(sampleData);
            Console.WriteLine($"\n\nPredicted Label value: {predictionResult.PredictedLabel} \nPredicted Label scores: [{String.Join(",", predictionResult.Score)}]\n\n");
        }
    }
}

